### ISSUE TITLE
Error al ejecutar código

### ISSUE THREAD

**Issue by luiocahoe** [martarodriguezhebles/trabajo01grupotd2023#1]
Al ejecutar la instrucción de la línea 26 aparece el siguiente error:
Error in crea.tablaX(c(50, 75, 110, 400, 65, 80, 90, 250, 80, 80, 80,  : 
  could not find function "crea.tablaX"
No se ha enlazado el archivo que crea la función.

**Comment by martarodriguezhebles** [comment]
ya esta solucionado, había que añadir el comando para poder leer dichas funciones.
